blank_issues_enabled: false

contact_links:
  - name: âœ¨ Request a new Feature
    url: https://forum.syncthing.net/
    about: To share your ideas to improve Syncthing-Fork, enjoy discussing them with the Syncthing Community and file an issue on GitHub when ready.

  - name: ðŸ’¬ Support Request or Ask a Question
    url: https://forum.syncthing.net/
    about: For general questions or support, please use the Syncthing Community Forum instead of creating an issue here.
